name: Maven Package

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run OWASP Dependency-Check with Maven
        run: mvn -B verify --file pom.xml
        # The OWASP Dependency-Check plugin is executed as part of the Maven build cycle.

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/action:1.0.${{ env.VERSION }} # Using VERSION variable

      - name: Scan the Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/action:1.0.${{ env.VERSION }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image
        if: success() # This step will only run if the previous Trivy scan is successful
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/action:1.0.${{ env.VERSION }} # Using VERSION variable

  increment_version:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}
    steps:
      - name: version increment
        id: increment_version_step
        uses: action-pack/increment@v2
        with:
          name: 'VERSION'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Export VERSION as an environment variable
        run: echo "VERSION=${{ steps.increment_version_step.outputs.new_value }}" >> $GITHUB_ENV
