name: Maven Package

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run OWASP Dependency-Check with Maven
        run: mvn -B verify --file pom.xml
        # The OWASP Dependency-Check plugin is executed as part of the Maven build cycle.


      - name: Run Maven package and SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar:sonar \
                  -Dsonar.projectKey=shayking_simple-java-maven-app \
                  -Dsonar.organization=shayking \
                  -Dsonar.host.url=https://sonarcloud.io


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install cosign
        uses: sigstore/cosign-installer@main



      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/action:1.0.${{ vars.VERSION }}

      - name: Scan Docker image with Snyk
        uses: snyk/actions/docker@master
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/action:1.0.${{ vars.VERSION }}
          args: --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Decode Cosign Private Key
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          echo "$COSIGN_PRIVATE_KEY" | base64 -d > cosign.key
          chmod 600 cosign.key

      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/action:1.0.${{ vars.VERSION }}

      - name: Sign Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign --key cosign.key --yes ${{ secrets.DOCKERHUB_USERNAME }}/action:1.0.${{ vars.VERSION }}







  increment_version:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}
    steps:
      - name: version increment
        uses: action-pack/increment@v2
        with:
          name: 'VERSION'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}




