# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run OWASP Dependency-Check with Maven
        run: mvn -B verify --file pom.xml
        # The OWASP Dependency-Check plugin is executed as part of the Maven build cycle.

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/action:1.0.${{ github.run_number }}

      - name: Scan Docker image with Trivy
        id: trivy_scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.docker_build.outputs.image }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image if scan successful
        if: steps.trivy_scan.outputs.exit-code == '0'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.docker_build.outputs.image }}

          
  increment_version:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}
    steps:
      - name: version increment
        uses: action-pack/increment@v2
        with:
          name: 'VERSION'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
